/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353535",
        "on-primary-fixed": "#002201",
        "on-background": "#e2e2e2",
        "secondary-fixed-dim": "#c8c6c5",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#00513f",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#303030",
        "inverse-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "on-secondary-container": "#b7b5b4",
        "primary-container": "#48ff48",
        "tertiary-fixed": "#24ffcd",
        "tertiary-container": "#00fbc9",
        "secondary-container": "#474746",
        "on-primary-fixed-variant": "#005307",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#002118",
        "tertiary-fixed-dim": "#00e0b3",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-primary": "#006e0c",
        "surface-tint": "#20e52f",
        "outline-variant": "#3c4b37",
        "primary-fixed": "#75ff69",
        "surface-variant": "#353535",
        "secondary": "#c8c6c5",
        "on-tertiary": "#00382b",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474746",
        "error-container": "#93000a",
        "surface-container": "#1f1f1f",
        "on-secondary": "#313030",
        "tertiary": "#eefff6",
        "on-tertiary-container": "#006f58",
        "on-surface": "#e2e2e2",
        "background": "#000000",
        "primary": "#48ff48",
        "primary-light": "#f3ffea",
        "on-error": "#690005",
        "on-primary": "#003a03",
        "primary-fixed-dim": "#20e52f",
        "outline": "#85957e",
        "surface-container-low": "#1b1b1b",
        "on-surface-variant": "#bbcbb2",
        "on-primary-container": "#00720d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "4px",
        "container-max": "1440px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "telemetry-md": ["JetBrains Mono", "monospace"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "display-hero": ["Archivo Narrow", "sans-serif"],
        "headline-lg-mobile": ["Archivo Narrow", "sans-serif"],
        "headline-lg": ["Archivo Narrow", "sans-serif"],
        "sans": ["Archivo Narrow", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-caps": ["11px", { "lineHeight": "12px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "telemetry-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "telemetry-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-hero": ["72px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-lg": ["40px", { "lineHeight": "44px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
