/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e9ddff",
        "secondary": "#ffb59a",
        "surface-container": "#1e1e31",
        "surface-dim": "#111125",
        "surface-container-highest": "#333348",
        "primary": "#dbfcff",
        "on-secondary-fixed-variant": "#802a00",
        "on-tertiary": "#3c0090",
        "on-surface": "#e2e0fb",
        "on-tertiary-fixed-variant": "#5700c9",
        "on-primary-container": "#006970",
        "on-error": "#690005",
        "on-primary": "#00363a",
        "surface-bright": "#37374c",
        "surface": "#111125",
        "on-background": "#e2e0fb",
        "secondary-container": "#ff5e07",
        "on-secondary-fixed": "#370e00",
        "on-tertiary-container": "#7213ff",
        "on-secondary-container": "#531900",
        "background": "#111125",
        "on-surface-variant": "#b9cacb",
        "outline": "#849495",
        "tertiary-container": "#e1d2ff",
        "primary-fixed": "#7df4ff",
        "secondary-fixed": "#ffdbce",
        "surface-tint": "#00dbe9",
        "tertiary-fixed-dim": "#d1bcff",
        "on-primary-fixed-variant": "#004f54",
        "inverse-primary": "#006970",
        "surface-container-lowest": "#0c0c1f",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#00dbe9",
        "error-container": "#93000a",
        "surface-variant": "#333348",
        "inverse-surface": "#e2e0fb",
        "on-secondary": "#5a1b00",
        "surface-container-high": "#28283c",
        "secondary-fixed-dim": "#ffb59a",
        "tertiary": "#faf3ff",
        "primary-container": "#00f0ff",
        "outline-variant": "#3b494b",
        "surface-container-low": "#1a1a2d",
        "on-primary-fixed": "#002022",
        "on-tertiary-fixed": "#23005b",
        "inverse-on-surface": "#2f2e43"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "48px",
        "unit": "4px",
        "xs": "4px",
        "container-max": "1200px",
        "sm": "8px",
        "lg": "24px",
        "orbital-gap": "32px",
        "md": "16px"
      },
      fontFamily: {
        "semantic-word": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "semantic-word": ["20px", { "lineHeight": "28px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
